version: '3'
services:
    db:
      image: postgres:latest
      container_name: postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: "${DB_USER_ID}"
        POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
        #POSTGRES_USER: "postgres"
        #POSTGRES_PASSWORD: "password"
      volumes:
        - ./data:/var/lib/postgresql/data